name: thesis
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  http: 0.13.3
  shared_preferences: 2.0.6
  pull_to_refresh: ^2.0.0
  fluttertoast: 8.0.7
  location: 4.3.0
  mapbox_gl: 0.11.0
  multi_select_flutter: ^4.0.0
  signalr_netcore: 0.1.7+2-nullsafety.2
  background_fetch: 1.0.1
  intl: 0.17.0
  flutter_launcher_icons: 0.9.1
  flutter_screenutil: ^5.0.0+2
  email_validator: 2.0.1
  google_fonts: 2.1.0

dependency_overrides:
  mapbox_gl:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      path: mapbox_gl_platform_interface
  mapbox_gl_web:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      path: mapbox_gl_web

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/home.png

  fonts:
    - family: Cups
      fonts:
        - asset: assets/icons/Cup.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900