name: thesis
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  http: 0.13.3
  shared_preferences: 2.0.6
  rxdart: 0.27.1
  fluttertoast: 8.0.7
  location: 4.3.0
  mapbox_gl: 0.11.0
  multiselect_formfield: 0.1.6
  signalr_netcore: 0.1.7+2-nullsafety.2
  flutter_spinkit: 5.0.0-nullsafety.0
  background_fetch: 1.0.1
  intl: 0.17.0
  flutter_launcher_icons: 0.9.1

dependency_overrides:
  mapbox_gl:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      path: mapbox_gl_platform_interface
  mapbox_gl_web:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      path: mapbox_gl_web

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/home.png
